//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hal-hazırki parolu yanlış daxil etmisiniz!.
        /// </summary>
        public static string current_password_incorrect {
            get {
                return ResourceManager.GetString("current_password_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil etdiyiniz məlumat sistemdə mövcuddur.
        /// </summary>
        public static string duplicate_data_exception {
            get {
                return ResourceManager.GetString("duplicate_data_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil edilmiş E-mail ilə istifadəçi artıq qeydiyyatdan keçmişdir..
        /// </summary>
        public static string duplicate_email {
            get {
                return ResourceManager.GetString("duplicate_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil edilmiş FİN kodu ilə istifadəçi artıq qeydiyyatdan keçmişdir..
        /// </summary>
        public static string duplicate_fin {
            get {
                return ResourceManager.GetString("duplicate_fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil edilmiş FİN kodu və E-mail ilə istifadəçi artıq qeydiyyatdan keçmişdir..
        /// </summary>
        public static string duplicate_fin_and_email {
            get {
                return ResourceManager.GetString("duplicate_fin_and_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyni adlı istifadəçi sistemdə mövcuddur.
        /// </summary>
        public static string duplicate_username {
            get {
                return ResourceManager.GetString("duplicate_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu məlumat ilə başlanılmış qeydiyyat tapılmadı..
        /// </summary>
        public static string error_dont_exist_data_in_redis {
            get {
                return ResourceManager.GetString("error_dont_exist_data_in_redis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu e-mail ilə başlanmış qeydiyyat tapılmadı..
        /// </summary>
        public static string error_dont_exist_email_data_in_redis {
            get {
                return ResourceManager.GetString("error_dont_exist_email_data_in_redis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birdəfəlik kodun cəhdlərinin sayı aşılıb.
        /// </summary>
        public static string error_otp_attempts_exceed {
            get {
                return ResourceManager.GetString("error_otp_attempts_exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birdəfəlik kodun vaxtı bitib.
        /// </summary>
        public static string error_otp_expired {
            get {
                return ResourceManager.GetString("error_otp_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birdəfəlik kodun təkrar göndərilə bilmədi.
        /// </summary>
        public static string error_otp_resend {
            get {
                return ResourceManager.GetString("error_otp_resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birdəfəlik kod düzgün deyil.
        /// </summary>
        public static string error_otp_verification {
            get {
                return ResourceManager.GetString("error_otp_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir dəfəlik kod ya yanlışdır, ya da vaxtı keçib..
        /// </summary>
        public static string error_otp_verification_or_expired {
            get {
                return ResourceManager.GetString("error_otp_verification_or_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil etdiyiniz məlumatın formatı düzgün deyil.
        /// </summary>
        public static string incorrect_format {
            get {
                return ResourceManager.GetString("incorrect_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fayl ölçüsü 4 MB-dan artıq ola bilməz!.
        /// </summary>
        public static string invalid_file_storage {
            get {
                return ResourceManager.GetString("invalid_file_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil etdiyiniz şifrənin formatı düzgün deyil! (Şifrənizdə ən azı 6 simvol , ən azı 1böyük hərf , ən azı1 kiçik hərf ,ən azı 1 simvol və ən azı 1 rəqəm istifadə etməlisiniz!).
        /// </summary>
        public static string invalid_password_exception {
            get {
                return ResourceManager.GetString("invalid_password_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat sistemdə tapılmadı.
        /// </summary>
        public static string not_found_entity {
            get {
                return ResourceManager.GetString("not_found_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat sistemdə tapılmadı.
        /// </summary>
        public static string object_not_found {
            get {
                return ResourceManager.GetString("object_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifrə və yeni şifrənin təkrarı eyni deyil!.
        /// </summary>
        public static string passwords_dont_match {
            get {
                return ResourceManager.GetString("passwords_dont_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenidən OTP göndərmək üçün təyin olunan vaxtı gözləməlisiniz!.
        /// </summary>
        public static string required_otp_time_exception {
            get {
                return ResourceManager.GetString("required_otp_time_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi adı və ya şifrəsi düzgün deyil.
        /// </summary>
        public static string username_password_incorrect {
            get {
                return ResourceManager.GetString("username_password_incorrect", resourceCulture);
            }
        }
    }
}
